// <auto-generated />
namespace CabinetVeterinar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1AdaugareUltilizator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1AdaugareUltilizator));
        
        string IMigrationMetadata.Id
        {
            get { return "202112031501473_1.AdaugareUltilizator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
