// <auto-generated />
namespace CabinetVeterinar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Modificare_coloane_utilizator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modificare_coloane_utilizator));
        
        string IMigrationMetadata.Id
        {
            get { return "202112171655475_Modificare_coloane_utilizator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
