// <auto-generated />
namespace CabinetVeterinar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Creare_tabel_programari : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creare_tabel_programari));
        
        string IMigrationMetadata.Id
        {
            get { return "202201251522263_Creare_tabel_programari"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
