// <auto-generated />
namespace CabinetVeterinar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modif_col : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modif_col));
        
        string IMigrationMetadata.Id
        {
            get { return "202205060533346_modif_col"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
