// <auto-generated />
namespace CabinetVeterinar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fisa_pacient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fisa_pacient));
        
        string IMigrationMetadata.Id
        {
            get { return "202206061130578_fisa_pacient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
